name: Sync Image to Aliyun  Example
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: dawncharles
        password: dawei19991108.
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy --override-arch=arm64/v8 docker://docker.io/python:3.12-alpine3.20 docker://registry.cn-hangzhou.aliyuncs.com/dawncharles/python:3.12-alpine3.22